<h1 align="center">Numpy lessons</h1>


In [1]:
import numpy as np

## Day 1

In [27]:
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3,4],[5,6,7,8]]) 
c=np.array([(1,2,3),(4,5,6)]) #both () and [] can be used
print(b)
print(c)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [4 5 6]]


- a.ndim = get dimensions
- a.shape = get shape
- a.dtype = get datatype
- a.itemsize = size of the data type 
- a.nbytes = array size
- a.size = number of elements

### Creating new arrays

In [30]:
#(3,4) is for rows and columns here

a=np.zeros((3, 4))
b=np.ones((3,4))
c=np.empty((3,4)) # creates a random array with garbage values

# to create a series array 
d=np.arange(10, 30, 5) #creates a 1d array from 10 to 30 with count gap of 5 (start,stop,gap)
e=np.linspace(0,2,9) #creates a 1d array of 9 random elements from 0 to 2 (start,stop,number_of_elements)

In [36]:
#creating a array from a function definition
def f(x,y):
    return 10 * x + y

In [37]:
b = np.fromfunction(f, (5, 4), dtype=int)

### Basic Operations

In [35]:
a=np.arange(1,40,10)
b=np.ones((1,4))
c=a-b #vectorized notation ie. c[i]=b[i]-a[i]
print(c)
d=c**2
e=a*b # * stands for element wise multiplication
print(e)
f=a @ b # @ and a.dot(b) stands for matrix multiplication

[[ 0. 10. 20. 30.]]
[[  0. 100. 400. 900.]]
[[ 1. 11. 21. 31.]]


### Accessing/Changing specific elements, rows, columns, etc


In [41]:
#Slicing
a[::-1] #reverse the array
a[:,::-1] #reverse the columns
a[::-1,:] #reverse the rows
a[::-1,::-1] #reverse the rows and columns

array([[5., 7., 0., 5.],
       [4., 8., 4., 3.],
       [9., 1., 9., 5.]])

In [40]:
#Shape manipulation
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
a.shape

(3, 4)

In [42]:
a.ravel() #flattens the array
a.reshape(2,6) #reshapes the array
a.T #transpose the array

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])